# Generated by Django 3.2.25 on 2024-12-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20241211_1253'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='advuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
